<?php

/**
 * BaseVideoSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $video_id
 * @property integer $song_id
 * @property Video $Video
 * @property Dancer $Dancer
 * 
 * @method integer   getVideoId()  Returns the current record's "video_id" value
 * @method integer   getSongId()   Returns the current record's "song_id" value
 * @method Video     getVideo()    Returns the current record's "Video" value
 * @method Dancer    getDancer()   Returns the current record's "Dancer" value
 * @method VideoSong setVideoId()  Sets the current record's "video_id" value
 * @method VideoSong setSongId()   Sets the current record's "song_id" value
 * @method VideoSong setVideo()    Sets the current record's "Video" value
 * @method VideoSong setDancer()   Sets the current record's "Dancer" value
 * 
 * @package    subyt
 * @subpackage model
 * @author     Eric Leclerc <eric.leclerc@gmail.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseVideoSong extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video_song');
        $this->hasColumn('video_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('song_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id'));

        $this->hasOne('Dancer', array(
             'local' => 'dancer_id',
             'foreign' => 'id'));
    }
}