<?php

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $state
 * @property Doctrine_Collection $Videos
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method string              getState()  Returns the current record's "state" value
 * @method Doctrine_Collection getVideos() Returns the current record's "Videos" collection
 * @method Event               setName()   Sets the current record's "name" value
 * @method Event               setState()  Sets the current record's "state" value
 * @method Event               setVideos() Sets the current record's "Videos" collection
 * 
 * @package    subyt
 * @subpackage model
 * @author     Eric Leclerc <eric.leclerc@gmail.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('state', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Video as Videos', array(
             'local' => 'id',
             'foreign' => 'event_id'));
    }
}