<?php

/**
 * BaseVideoTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $video_id
 * @property integer $tag_id
 * @property Video $Video
 * @property Tag $Tag
 * 
 * @method integer  getVideoId()  Returns the current record's "video_id" value
 * @method integer  getTagId()    Returns the current record's "tag_id" value
 * @method Video    getVideo()    Returns the current record's "Video" value
 * @method Tag      getTag()      Returns the current record's "Tag" value
 * @method VideoTag setVideoId()  Sets the current record's "video_id" value
 * @method VideoTag setTagId()    Sets the current record's "tag_id" value
 * @method VideoTag setVideo()    Sets the current record's "Video" value
 * @method VideoTag setTag()      Sets the current record's "Tag" value
 * 
 * @package    subyt
 * @subpackage model
 * @author     Eric Leclerc <eric.leclerc@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVideoTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video_tag');
        $this->hasColumn('video_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id'));
    }
}