<?php

/**
 * BaseVideoDancer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $video_id
 * @property integer $dancer_id
 * @property Video $Video
 * @property Dancer $Dancer
 * 
 * @method integer     getVideoId()   Returns the current record's "video_id" value
 * @method integer     getDancerId()  Returns the current record's "dancer_id" value
 * @method Video       getVideo()     Returns the current record's "Video" value
 * @method Dancer      getDancer()    Returns the current record's "Dancer" value
 * @method VideoDancer setVideoId()   Sets the current record's "video_id" value
 * @method VideoDancer setDancerId()  Sets the current record's "dancer_id" value
 * @method VideoDancer setVideo()     Sets the current record's "Video" value
 * @method VideoDancer setDancer()    Sets the current record's "Dancer" value
 * 
 * @package    subyt
 * @subpackage model
 * @author     Eric Leclerc <eric.leclerc@gmail.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseVideoDancer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video_dancer');
        $this->hasColumn('video_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('dancer_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id'));

        $this->hasOne('Dancer', array(
             'local' => 'dancer_id',
             'foreign' => 'id'));
    }
}