<?php

/**
 * BaseSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $artist
 * @property Doctrine_Collection $Videos
 * @property Doctrine_Collection $VideoSongs
 * 
 * @method string              getTitle()      Returns the current record's "title" value
 * @method string              getArtist()     Returns the current record's "artist" value
 * @method Doctrine_Collection getVideos()     Returns the current record's "Videos" collection
 * @method Doctrine_Collection getVideoSongs() Returns the current record's "VideoSongs" collection
 * @method Song                setTitle()      Sets the current record's "title" value
 * @method Song                setArtist()     Sets the current record's "artist" value
 * @method Song                setVideos()     Sets the current record's "Videos" collection
 * @method Song                setVideoSongs() Sets the current record's "VideoSongs" collection
 * 
 * @package    subyt
 * @subpackage model
 * @author     Eric Leclerc <eric.leclerc@gmail.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseSong extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('song');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('artist', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Video as Videos', array(
             'refClass' => 'VideoSong',
             'local' => 'song_id',
             'foreign' => 'video_id'));

        $this->hasMany('VideoSong as VideoSongs', array(
             'local' => 'id',
             'foreign' => 'song_id'));
    }
}