generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Video
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          video
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:  
        display:  [=youtube_title, published, created_at]
        sort:     [created_at, desc]
      filter:  
        display:  [youtube_title, created_at] 
      form:    ~
      edit:    ~ 
      new:     ~
