generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Dancer
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dancer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        display:  [name, website]
      list:    
        display:  [=name, website]
        sort:     [name, asc]
      filter:  
        display:  [name, website]
      form:    
        display:  [name, website]
      edit:    ~
      new:     ~
